//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionSIPA1.WsTipoCambio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class InfoVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionSIPA1.WsTipoCambio.Variable[] VariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionSIPA1.WsTipoCambio.Var[] CambioDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionSIPA1.WsTipoCambio.VarDolar[] CambioDolarField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AplicacionSIPA1.WsTipoCambio.Variable[] Variables {
            get {
                return this.VariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariablesField, value) != true)) {
                    this.VariablesField = value;
                    this.RaisePropertyChanged("Variables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AplicacionSIPA1.WsTipoCambio.Var[] CambioDia {
            get {
                return this.CambioDiaField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDiaField, value) != true)) {
                    this.CambioDiaField = value;
                    this.RaisePropertyChanged("CambioDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AplicacionSIPA1.WsTipoCambio.VarDolar[] CambioDolar {
            get {
                return this.CambioDolarField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDolarField, value) != true)) {
                    this.CambioDolarField = value;
                    this.RaisePropertyChanged("CambioDolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Variable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Var : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta {
            get {
                return this.ventaField;
            }
            set {
                if ((this.ventaField.Equals(value) != true)) {
                    this.ventaField = value;
                    this.RaisePropertyChanged("venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra {
            get {
                return this.compraField;
            }
            set {
                if ((this.compraField.Equals(value) != true)) {
                    this.compraField = value;
                    this.RaisePropertyChanged("compra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class VarDolar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float referenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia {
            get {
                return this.referenciaField;
            }
            set {
                if ((this.referenciaField.Equals(value) != true)) {
                    this.referenciaField = value;
                    this.RaisePropertyChanged("referencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class DataVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionSIPA1.WsTipoCambio.Var[] VarsField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AplicacionSIPA1.WsTipoCambio.Var[] Vars {
            get {
                return this.VarsField;
            }
            set {
                if ((object.ReferenceEquals(this.VarsField, value) != true)) {
                    this.VarsField = value;
                    this.RaisePropertyChanged("Vars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="WsTipoCambio.TipoCambioSoap")]
    public interface TipoCambioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesDisponiblesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesResponse VariablesDisponibles(AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesResponse> VariablesDisponiblesAsync(AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        AplicacionSIPA1.WsTipoCambio.VariablesResponse Variables(AplicacionSIPA1.WsTipoCambio.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.VariablesResponse> VariablesAsync(AplicacionSIPA1.WsTipoCambio.VariablesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialResponse TipoCambioFechaInicial(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        AplicacionSIPA1.WsTipoCambio.TipoCambioRangoResponse TipoCambioRango(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioRangoResponse> TipoCambioRangoAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaResponse TipoCambioFechaInicialMoneda(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaResponse TipoCambioRangoMoneda(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        AplicacionSIPA1.WsTipoCambio.TipoCambioDiaResponse TipoCambioDia(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioDiaResponse> TipoCambioDiaAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaStringResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringResponse TipoCambioDiaString(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest() {
        }
        
        public VariablesDisponiblesRequest(AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody {
        
        public VariablesDisponiblesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse() {
        }
        
        public VariablesDisponiblesResponse(AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionSIPA1.WsTipoCambio.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody() {
        }
        
        public VariablesDisponiblesResponseBody(AplicacionSIPA1.WsTipoCambio.InfoVariable VariablesDisponiblesResult) {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.VariablesRequestBody Body;
        
        public VariablesRequest() {
        }
        
        public VariablesRequest(AplicacionSIPA1.WsTipoCambio.VariablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody() {
        }
        
        public VariablesRequestBody(int variable) {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.VariablesResponseBody Body;
        
        public VariablesResponse() {
        }
        
        public VariablesResponse(AplicacionSIPA1.WsTipoCambio.VariablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionSIPA1.WsTipoCambio.InfoVariable VariablesResult;
        
        public VariablesResponseBody() {
        }
        
        public VariablesResponseBody(AplicacionSIPA1.WsTipoCambio.InfoVariable VariablesResult) {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest() {
        }
        
        public TipoCambioFechaInicialRequest(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody() {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit) {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse() {
        }
        
        public TipoCambioFechaInicialResponse(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody() {
        }
        
        public TipoCambioFechaInicialResponseBody(AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioFechaInicialResult) {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest() {
        }
        
        public TipoCambioRangoRequest(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody() {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse() {
        }
        
        public TipoCambioRangoResponse(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody() {
        }
        
        public TipoCambioRangoResponseBody(AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioRangoResult) {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest() {
        }
        
        public TipoCambioFechaInicialMonedaRequest(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody() {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda) {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse() {
        }
        
        public TipoCambioFechaInicialMonedaResponse(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody() {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioFechaInicialMonedaResult) {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest() {
        }
        
        public TipoCambioRangoMonedaRequest(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody() {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse() {
        }
        
        public TipoCambioRangoMonedaResponse(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody() {
        }
        
        public TipoCambioRangoMonedaResponseBody(AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioRangoMonedaResult) {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest() {
        }
        
        public TipoCambioDiaRequest(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody {
        
        public TipoCambioDiaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse() {
        }
        
        public TipoCambioDiaResponse(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AplicacionSIPA1.WsTipoCambio.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody() {
        }
        
        public TipoCambioDiaResponseBody(AplicacionSIPA1.WsTipoCambio.InfoVariable TipoCambioDiaResult) {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest() {
        }
        
        public TipoCambioDiaStringRequest(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody {
        
        public TipoCambioDiaStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse() {
        }
        
        public TipoCambioDiaStringResponse(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody() {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult) {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoCambioSoapChannel : AplicacionSIPA1.WsTipoCambio.TipoCambioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<AplicacionSIPA1.WsTipoCambio.TipoCambioSoap>, AplicacionSIPA1.WsTipoCambio.TipoCambioSoap {
        
        public TipoCambioSoapClient() {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesResponse AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.VariablesDisponibles(AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponibles(request);
        }
        
        public AplicacionSIPA1.WsTipoCambio.InfoVariable VariablesDisponibles() {
            AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequest inValue = new AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequestBody();
            AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesResponse retVal = ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).VariablesDisponibles(inValue);
            return retVal.Body.VariablesDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesResponse> AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.VariablesDisponiblesAsync(AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesResponse> VariablesDisponiblesAsync() {
            AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequest inValue = new AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.VariablesDisponiblesRequestBody();
            return ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSIPA1.WsTipoCambio.VariablesResponse AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.Variables(AplicacionSIPA1.WsTipoCambio.VariablesRequest request) {
            return base.Channel.Variables(request);
        }
        
        public AplicacionSIPA1.WsTipoCambio.InfoVariable Variables(int variable) {
            AplicacionSIPA1.WsTipoCambio.VariablesRequest inValue = new AplicacionSIPA1.WsTipoCambio.VariablesRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.VariablesRequestBody();
            inValue.Body.variable = variable;
            AplicacionSIPA1.WsTipoCambio.VariablesResponse retVal = ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).Variables(inValue);
            return retVal.Body.VariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.VariablesResponse> AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.VariablesAsync(AplicacionSIPA1.WsTipoCambio.VariablesRequest request) {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.VariablesResponse> VariablesAsync(int variable) {
            AplicacionSIPA1.WsTipoCambio.VariablesRequest inValue = new AplicacionSIPA1.WsTipoCambio.VariablesRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialResponse AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioFechaInicial(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicial(request);
        }
        
        public AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioFechaInicial(string fechainit) {
            AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialResponse retVal = ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicial(inValue);
            return retVal.Body.TipoCambioFechaInicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialResponse> AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioFechaInicialAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit) {
            AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSIPA1.WsTipoCambio.TipoCambioRangoResponse AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioRango(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRango(request);
        }
        
        public AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioRango(string fechainit, string fechafin) {
            AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            AplicacionSIPA1.WsTipoCambio.TipoCambioRangoResponse retVal = ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioRango(inValue);
            return retVal.Body.TipoCambioRangoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioRangoResponse> AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioRangoAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin) {
            AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaResponse AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioFechaInicialMoneda(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMoneda(request);
        }
        
        public AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioFechaInicialMoneda(string fechainit, int moneda) {
            AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaResponse retVal = ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialMoneda(inValue);
            return retVal.Body.TipoCambioFechaInicialMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaResponse> AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda) {
            AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaResponse AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioRangoMoneda(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMoneda(request);
        }
        
        public AplicacionSIPA1.WsTipoCambio.DataVariable TipoCambioRangoMoneda(string fechainit, string fechafin, int moneda) {
            AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaResponse retVal = ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoMoneda(inValue);
            return retVal.Body.TipoCambioRangoMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaResponse> AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioRangoMonedaAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda) {
            AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSIPA1.WsTipoCambio.TipoCambioDiaResponse AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioDia(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDia(request);
        }
        
        public AplicacionSIPA1.WsTipoCambio.InfoVariable TipoCambioDia() {
            AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequestBody();
            AplicacionSIPA1.WsTipoCambio.TipoCambioDiaResponse retVal = ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioDia(inValue);
            return retVal.Body.TipoCambioDiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioDiaResponse> AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioDiaAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioDiaResponse> TipoCambioDiaAsync() {
            AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioDiaRequestBody();
            return ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringResponse AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioDiaString(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaString(request);
        }
        
        public string TipoCambioDiaString() {
            AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequestBody();
            AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringResponse retVal = ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaString(inValue);
            return retVal.Body.TipoCambioDiaStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringResponse> AplicacionSIPA1.WsTipoCambio.TipoCambioSoap.TipoCambioDiaStringAsync(AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync() {
            AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequest inValue = new AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequest();
            inValue.Body = new AplicacionSIPA1.WsTipoCambio.TipoCambioDiaStringRequestBody();
            return ((AplicacionSIPA1.WsTipoCambio.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
    }
}
